/**
 * Persistence Layer - Store Reasoning Results Back to Obsidian
 * Saves insights, patterns, and reasoning back to vault
 * Maintains pattern index for next iteration
 */

const fs = require('fs');
const path = require('path');

class ObsidianWriter {
  constructor(vaultPath = null) {
    if (!vaultPath) {
      const home = require('os').homedir();
      vaultPath = path.join(home, 'Obsidian Vaults', 'My Second Brain');
    }
    this.vaultPath = vaultPath;
    this.patternIndexFile = path.join(vaultPath, '20 Patterns', '_NEURAL_INDEX.md');
    this.insightsDir = path.join(vaultPath, '30 Memory');
  }

  /**
   * Save reasoning result as a new note
   */
  saveReasoning(result) {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `neural-reasoning-${timestamp}.md`;
      const filePath = path.join(this.insightsDir, filename);

      let content = `---
type: neural-reasoning
created: ${new Date().toISOString()}
problem: "${result.problem}"
depth: ${result.depth || 1}
---

# Neural Reasoning: ${result.problem}

## Thinking Process

\`\`\`
${result.thinking || 'No thinking recorded'}
\`\`\`

## Response

${result.response || 'No response generated'}

## Extracted Insights

${result.insights.map((i, idx) => `${idx + 1}. ${i}`).join('\n')}

## Metadata

- **Timestamp**: ${new Date().toISOString()}
- **Tokens Used**: ${result.tokensUsed || 0}
- **Quality Score**: ${(result.quality?.score || 0).toFixed(2)}

---

*Generated by Neural Engine*
`;

      fs.writeFileSync(filePath, content);
      console.log(`[NeuralEngine] Saved reasoning to ${filename}`);
      return filename;
    } catch (err) {
      console.error(`Failed to save reasoning: ${err.message}`);
      return null;
    }
  }

  /**
   * Update pattern index with new patterns
   */
  updatePatternIndex(firedPatterns) {
    try {
      let indexContent = this.readOrCreateIndex();

      // Add entries for each fired pattern
      for (const pattern of firedPatterns) {
        const entry = `- **${pattern.pattern}** (confidence: ${(pattern.confidence * 100).toFixed(0)}%, domain: ${pattern.domain}) - [[${pattern.relatedFile || 'Unlinked'}]]`;

        // Avoid duplicates
        if (!indexContent.includes(`**${pattern.pattern}**`)) {
          indexContent += `\n${entry}`;
        }
      }

      fs.writeFileSync(this.patternIndexFile, indexContent);
      console.log(`[NeuralEngine] Updated pattern index`);
    } catch (err) {
      console.error(`Failed to update pattern index: ${err.message}`);
    }
  }

  /**
   * Read or create pattern index
   */
  readOrCreateIndex() {
    try {
      if (fs.existsSync(this.patternIndexFile)) {
        return fs.readFileSync(this.patternIndexFile, 'utf-8');
      }
    } catch (err) {
      console.error(`Failed to read index: ${err.message}`);
    }

    // Create new index
    const defaultIndex = `# Neural Pattern Index

Generated by Live Neural Engine

## Active Patterns

Patterns are activated when matching incoming input.

`;

    try {
      fs.writeFileSync(this.patternIndexFile, defaultIndex);
    } catch (err) {
      console.error(`Failed to create index file: ${err.message}`);
    }

    return defaultIndex;
  }

  /**
   * Save insight as a separate note
   */
  saveInsight(insight, source = 'reasoning') {
    try {
      const timestamp = Date.now();
      const slug = insight
        .substring(0, 50)
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '-');
      const filename = `insight-${slug}-${timestamp}.md`;
      const filePath = path.join(this.insightsDir, filename);

      const content = `---
type: insight
source: ${source}
created: ${new Date().toISOString()}
---

# ${insight}

## Insight

${insight}

---

*Discovered by Neural Engine*
`;

      fs.writeFileSync(filePath, content);
      return filename;
    } catch (err) {
      console.error(`Failed to save insight: ${err.message}`);
      return null;
    }
  }

  /**
   * Create daily neural report
   */
  saveDailyReport(sessionData) {
    try {
      const today = new Date().toISOString().split('T')[0];
      const reportFile = path.join(
        this.insightsDir,
        `neural-report-${today}.md`
      );

      let content = `# Neural Engine Daily Report - ${today}

## Session Summary

- **Duration**: ${sessionData.duration || 'Unknown'}
- **Queries Processed**: ${sessionData.queriesProcessed || 0}
- **Patterns Fired**: ${sessionData.patternsFired || 0}
- **Insights Generated**: ${sessionData.insightsGenerated || 0}

## Top Patterns

${(sessionData.topPatterns || [])
  .map((p, i) => `${i + 1}. **${p.pattern}** (${(p.confidence * 100).toFixed(0)}%)`)
  .join('\n')}

## Key Insights

${(sessionData.keyInsights || []).map(i => `- ${i}`).join('\n')}

## Next Session

Based on today's reasoning, focus on:

${(sessionData.recommendations || []).map(r => `- [ ] ${r}`).join('\n')}

---

*Generated by Live Neural Engine*
`;

      fs.writeFileSync(reportFile, content);
      console.log(`[NeuralEngine] Saved daily report`);
      return reportFile;
    } catch (err) {
      console.error(`Failed to save daily report: ${err.message}`);
      return null;
    }
  }

  /**
   * Link insight to related notes
   */
  createBacklink(noteFile, relatedFiles = []) {
    try {
      const content = fs.readFileSync(noteFile, 'utf-8');
      let updated = content;

      // Add backlinks section
      if (!content.includes('## Related')) {
        let backlinks = '\n\n## Related Notes\n\n';
        for (const relFile of relatedFiles) {
          const cleanName = path.basename(relFile, '.md');
          backlinks += `- [[${cleanName}]]\n`;
        }
        updated += backlinks;
      }

      fs.writeFileSync(noteFile, updated);
      return true;
    } catch (err) {
      console.error(`Failed to create backlink: ${err.message}`);
      return false;
    }
  }
}

module.exports = ObsidianWriter;
